name: Unit Tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  docker-rspec:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.3
          - 3.2
          - 3.1
          - '3.0' # quoted to avoid interpretation as "3"
        docker_version:
          - ':26.'
          - ':27.'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: install docker
        env:
          DOCKER_VERSION: ${{ matrix.docker_version }}
        run: |
          set -x
          sudo apt-get remove -y docker docker-engine docker.io containerd runc ||:
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update -y
          sudo apt-cache gencaches
          sudo apt-get install -y docker-ce=$( apt-cache madison docker-ce | grep -e $DOCKER_VERSION | cut -f 2 -d '|' | head -1 | sed 's/\s//g' )
          if [ $? -ne 0 ]; then
            echo "Error: Could not install ${DOCKER_VERSION}"
            echo "Available docker versions:"
            apt-cache madison docker-ce
            exit 1
          fi
          sudo systemctl start docker
      - name: spec tests
        run: bundle exec rake

  podman-rspec:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.3
          - 3.2
          - 3.1
          - '3.0'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: install podman
        run: sudo ./script/install_podman.sh
      - name: spec tests
        run: bundle exec rake
