name: Unit Tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  docker-rspec:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.3
          - 3.2
          - 3.1
          - '3.0' # quoted to avoid interpretation as "3"
        docker_version:
          - ':26.'
          - ':27.'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: install docker
        env:
          DOCKER_VERSION: ${{ matrix.docker_version }}
        run: sudo ./script/install_docker.sh "${DOCKER_VERSION}"
      - name: spec tests
        run: bundle exec rake

  podman-rspec:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.3
          - 3.2
          - 3.1
          - '3.0'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: install podman
        run: sudo ./script/install_podman.sh
      - name: spec tests
        run: bundle exec rake
